#spring:
#    datasource:
#      url: jdbc:oracle:thin:@localhost:1521/xe
#      username: zhidao
#      password: zhidao
#      driver-class-name: oracle.jdbc.OracleDriver
#    thymeleaf:
#       cache: false
#       mode: LEGACYHTML5
#mybatis:
#  type-aliases-package: com.pjb.bean
#  mapper-locations: classpath*:com.pjb.mapper/*.xml

spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: system
      driver-class-name: org.postgresql.Driver
    thymeleaf:
       cache: false
       mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.pjb.bean
  mapper-locations: classpath*:com.pjb.mapper/*.xml